apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: imagynetech/eatlater-api-gateway:1.12.0
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: '3000'
            - name: RMQ_URI
              value: amqp://user:user@eatlater-rabbitmq:5672
            - name: JWT_EXPIRATION
              value: '360000'
            - name: JWT_SECRET
              value: 64a5b5676eb9329c8978d3367fd7e1df5404ff886d16c0bc03edf7cc
            - name: RMQ_NOTIFICATION_QUEUE
              value: NOTIFICATION
            - name: RMQ_API_QUEUE
              value: API
            - name: RMQ_USERS_QUEUE
              value: USERS
            - name: RMQ_VENDORS_QUEUE
              value: VENDORS
            - name: RMQ_LISTINGS_QUEUE
              value: LISTINGS
            - name: RMQ_ORDERS_QUEUE
              value: ORDERS
      imagePullSecrets:
        - name: regcred
