version: v1

issue:
  labels:
    - prefix: kind
      list:
        - feature
        - bug
        - question
        - fix
        - chore
        - docs
        - refactor
        - dependencies
        - packages
      multiple: false
      needs: true
      author_association:
        author: true
        collaborator: true
        member: true
        owner: true

    - prefix: area
      list:
        - core
        - notification-service
        - admin-gateway
        - admin-service
        - api-gateway
        - drivers-service
        - listings-service
        - location-service
        - orders-service
        - payment-service
        - reviews-service
        - users-service
        - vendor-gateway
        - vendors-service
      multiple: true
      needs: true
      author_association:
        author: true
        collaborator: true
        member: true
        owner: true

    - prefix: priority
      multiple: true
      list: [ "urgent-now", "important-soon", "low" ]
      needs:
        comment: |
          @$AUTHOR: Thanks for opening an issue, an appropriate priority will be added soon.
          
          The priority labels can be added by foundation members by writing /priority [type] in a comment.
      author_association:
        collaborator: true
        member: true
        owner: true

  chat_ops:
    - cmd: /close
      type: close
      author_association:
        author: true
        collaborator: true
        member: true
        owner: true

    - cmd: /duplicate
      type: close
      author_association:
        collaborator: true
        member: true
        owner: true

    - cmd: /duplicate
      type: comment
      comment: |
        @$ISSUE_AUTHOR: This issue has been marked duplicate by @$AUTHOR, if you think this is a mistake, please reopen it!
      author_association:
        collaborator: true
        member: true
        owner: true

    - cmd: /duplicate
      type: label
      label:
        add: duplicate
      author_association:
        collaborator: true
        member: true
        owner: true

    - cmd: /cc
      type: none

    - cmd: /assign
      type: assign
      author_association:
        collaborator: true
        member: true
        owner: true

  captures:
    - regex: '\W*v?(\d+\.\d+\.\d+)\W*'
      github_release: true
      ignore_case: true
      label: 'version/$CAPTURED'

    - regex: '\W*iOS\W*'
      label: 'platform/ios'
      ignore_case: true

    - regex: '\W*Android\W*'
      label: 'platform/android'
      ignore_case: true

pull_request:
  labels:
    - prefix: kind
      multiple: false
      list:
        - feature
        - fix
        - chore
        - docs
        - refactor
        - dependencies
        - packages
      needs:
        comment: |
          @$AUTHOR: There are no 'kind' label on this PR. You need a 'kind' label to generate the release automatically.

          * `/kind feature`
          * `/kind fix`
          * `/kind chore`
          * `/kind docs`
          * `/kind refactor`
          * `/kind dependencies`
          * `/kind packages`
        status:
          context: "Governance / Kind Label"
          description:
            success: Ready for review & merge.
            failure: Missing 'kind' label for release generation.
      author_association:
        author: true
        collaborator: true
        member: true
        owner: true

    - prefix: priority
      multiple: false
      list: [ "urgent-now", "important-soon", "low" ]
      author_association:
        collaborator: true
        member: true
        owner: true

  chat_ops:
    - cmd: /close
      type: close
      author_association:
        author: true
        collaborator: true
        member: true
        owner: true

    - cmd: /cc
      type: none

    - cmd: /request
      type: review
      author_association:
        collaborator: true
        member: true
        owner: true
