version: 0.2
phases:
  pre-build:
    commands:
      - aws ecr get-login-password --region af-south-1 | docker login --username AWS --password-stdin 814105780686.dkr.ecr.af-south-1.amazonaws.com
  build:
    commands:
      - docker build -t admin-gateway -f ./apps/admin-gateway/Dockerfile .
      - docker tag admin-gateway:latest 814105780686.dkr.ecr.af-south-1.amazonaws.com/admin-gateway:latest
      - docker build -t admin-service -f ./apps/admin-service/Dockerfile .
      - docker tag admin-service:latest 814105780686.dkr.ecr.af-south-1.amazonaws.com/admin-service:latest
      - docker build -t api-gateway -f ./apps/api-gateway/Dockerfile .
      - docker tag api-gateway:latest 814105780686.dkr.ecr.af-south-1.amazonaws.com/api-gateway:latest
      - docker build -t drivers-service -f ./apps/drivers-service/Dockerfile .
      - docker tag drivers-service:latest 814105780686.dkr.ecr.af-south-1.amazonaws.com/drivers-service:latest
      - docker build -t listings-service -f ./apps/listings-service/Dockerfile .
      - docker tag listings-service:latest 814105780686.dkr.ecr.af-south-1.amazonaws.com/listings-service:latest
      - docker build -t location-service -f ./apps/location-service/Dockerfile .
      - docker tag location-service:latest 814105780686.dkr.ecr.af-south-1.amazonaws.com/location-service:latest
      - docker build -t notification-service -f ./apps/notification-service/Dockerfile .
      - docker tag notification-service:latest 814105780686.dkr.ecr.af-south-1.amazonaws.com/notification-service:latest
      - docker build -t orders-service -f ./apps/orders-service/Dockerfile .
      - docker tag orders-service:latest 814105780686.dkr.ecr.af-south-1.amazonaws.com/orders-service:latest
      - docker build -t payment-service -f ./apps/payment-service/Dockerfile .
      - docker tag payment-service:latest 814105780686.dkr.ecr.af-south-1.amazonaws.com/payment-service:latest
      - docker build -t reviews-service -f ./apps/reviews-service/Dockerfile .
      - docker tag reviews-service:latest 814105780686.dkr.ecr.af-south-1.amazonaws.com/reviews-service:latest
      - docker build -t users-service -f ./apps/users-service/Dockerfile .
      - docker tag users-service:latest 814105780686.dkr.ecr.af-south-1.amazonaws.com/users-service:latest
      - docker build -t vendors-service -f ./apps/vendors-service/Dockerfile .
      - docker tag vendors-service:latest 814105780686.dkr.ecr.af-south-1.amazonaws.com/vendors-service:latest
      - docker build -t vendor-gateway -f ./apps/vendor-gateway/Dockerfile .
      - docker tag vendor-gateway:latest 814105780686.dkr.ecr.af-south-1.amazonaws.com/vendor-gateway:latest
  post_build:
    commands:
      - docker push 814105780686.dkr.ecr.af-south-1.amazonaws.com/admin-gateway:latest
      - docker push 814105780686.dkr.ecr.af-south-1.amazonaws.com/admin-service:latest
      - docker push 814105780686.dkr.ecr.af-south-1.amazonaws.com/vendor-gateway:latest
      - docker push 814105780686.dkr.ecr.af-south-1.amazonaws.com/vendors-service:latest
      - docker push 814105780686.dkr.ecr.af-south-1.amazonaws.com/reviews-service:latest
      - docker push 814105780686.dkr.ecr.af-south-1.amazonaws.com/payment-service:latest
      - docker push 814105780686.dkr.ecr.af-south-1.amazonaws.com/orders-service:latest
      - docker push 814105780686.dkr.ecr.af-south-1.amazonaws.com/notification-service:latest
      - docker push 814105780686.dkr.ecr.af-south-1.amazonaws.com/location-service:latest
      - docker push 814105780686.dkr.ecr.af-south-1.amazonaws.com/listings-service:latest
      - docker push 814105780686.dkr.ecr.af-south-1.amazonaws.com/users-service:latest
      - docker push 814105780686.dkr.ecr.af-south-1.amazonaws.com/drivers-service:latest
      - docker push 814105780686.dkr.ecr.af-south-1.amazonaws.com/api-gateway:latest


