services:
  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
      target: development
    command: 'npm run start:dev api-gateway'
    env_file:
      - ./apps/api-gateway/.env
    depends_on:
      - rabbitmq
    volumes:
      - '.:/usr/src/app'
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    networks:
      - app-tier
  vendors-gateway:
    build:
      context: .
      dockerfile: ./apps/vendor-gateway/Dockerfile
      target: development
    command: 'npm run start:dev vendor-gateway'
    env_file:
      - ./apps/vendor-gateway/.env
    depends_on:
      - rabbitmq
    volumes:
      - '.:/usr/src/app'
      - /usr/src/app/node_modules
    ports:
      - '3001:3001'
    networks:
      - app-tier
  admin-gateway:
    build:
      context: .
      dockerfile: ./apps/admin-gateway/Dockerfile
      target: development
    command: 'npm run start:dev admin-gateway'
    env_file:
      - ./apps/admin-gateway/.env
    depends_on:
      - rabbitmq
    volumes:
      - '.:/usr/src/app'
      - /usr/src/app/node_modules
    ports:
      - '3002:3002'
    networks:
      - app-tier
  users-service:
    build:
      context: .
      dockerfile: ./apps/users-service/Dockerfile
      target: development
    command: 'npm run start:dev users-service'
    env_file:
      - ./apps/users-service/.env
    depends_on:
      - api-gateway
      - users-db
      - rabbitmq
    volumes:
      - '.:/usr/src/app'
      - /usr/src/app/node_modules
    networks:
      - app-tier
  notification-service:
    build:
      context: .
      dockerfile: ./apps/notification-service/Dockerfile
      target: development
    command: 'npm run start:dev notification-service'
    env_file:
      - ./apps/notification-service/.env
    depends_on:
      - api-gateway
      - rabbitmq
    volumes:
      - '.:/usr/src/app'
      - /usr/src/app/node_modules
    networks:
      - app-tier
  reviews-service:
    build:
      context: .
      dockerfile: ./apps/reviews-service/Dockerfile
      target: development
    command: 'npm run start:dev reviews-service'
    env_file:
      - ./apps/reviews-service/.env
    depends_on:
      - api-gateway
      - vendors-gateway
      - admin-gateway
      - rabbitmq
      - reviews-db
    volumes:
      - '.:/usr/src/app'
      - /usr/src/app/node_modules
    networks:
      - app-tier
  vendors-service:
    build:
      context: .
      dockerfile: ./apps/vendors-service/Dockerfile
      target: development
    command: 'npm run start:dev vendors-service'
    env_file:
      - ./apps/vendors-service/.env
    depends_on:
      - vendors-gateway
      - vendors-db
      - rabbitmq
    volumes:
      - '.:/usr/src/app'
      - /usr/src/app/node_modules
    networks:
      - app-tier
  admin-service:
    build:
      context: .
      dockerfile: ./apps/admin-service/Dockerfile
      target: development
    command: 'npm run start:dev admin-service'
    env_file:
      - ./apps/admin-service/.env
    depends_on:
      - admin-db
      - admin-gateway
      - rabbitmq
    volumes:
      - '.:/usr/src/app'
      - /usr/src/app/node_modules
    networks:
      - app-tier
  listings-service:
    build:
      context: .
      dockerfile: apps/listings-service/Dockerfile
      target: development
    command: 'npm run start:dev listings-service'
    env_file:
      - apps/listings-service/.env
    depends_on:
      - listings-db
      - vendors-gateway
      - rabbitmq
    volumes:
      - '.:/usr/src/app'
      - /usr/src/app/node_modules
    networks:
      - app-tier
  orders-service:
    build:
      context: .
      dockerfile: apps/orders-service/Dockerfile
      target: development
    command: 'npm run start:dev orders-service'
    env_file:
      - apps/orders-service/.env
    depends_on:
      - orders-db
      - api-gateway
      - rabbitmq
    volumes:
      - '.:/usr/src/app'
      - /usr/src/app/node_modules
    networks:
      - app-tier

  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-tier
  users-db:
    image: bitnami/postgresql:14
    ports:
      - '5432'
    environment:
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_PASSWORD=root@123
      - POSTGRESQL_DATABASE=users
    volumes:
      - pg_data:/var/lib/postgresql
    networks:
      - app-tier
  vendors-db:
    image: bitnami/postgresql:14
    ports:
      - '5432'
    environment:
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_PASSWORD=root@123
      - POSTGRESQL_DATABASE=vendors
    volumes:
      - pg_data:/var/lib/postgresql
    networks:
      - app-tier
  admin-db:
    image: bitnami/postgresql:14
    ports:
      - '5432'
    environment:
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_PASSWORD=root@123
      - POSTGRESQL_DATABASE=admin
    volumes:
      - pg_data:/var/lib/postgresql
    networks:
      - app-tier
  listings-db:
    image: bitnami/postgresql:14
    ports:
      - '5432'
    environment:
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_PASSWORD=root@123
      - POSTGRESQL_DATABASE=listings
    volumes:
      - pg_data:/var/lib/postgresql
    networks:
      - app-tier
  orders-db:
    image: bitnami/postgresql:14
    ports:
      - '5432'
    environment:
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_PASSWORD=root@123
      - POSTGRESQL_DATABASE=orders
    volumes:
      - pg_data:/var/lib/postgresql
    networks:
      - app-tier
  reviews-db:
    image: bitnami/postgresql:14
    ports:
      - '5432'
    environment:
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_PASSWORD=root@123
      - POSTGRESQL_DATABASE=orders
    volumes:
      - pg_data:/var/lib/postgresql
    networks:
      - app-tier
volumes:
  rabbitmq_data:
    driver: local
  pg_data:
    driver: local
networks:
  app-tier:
    driver: bridge
