POST http://localhost:3001/
Content-Type: application/json

{
  "firstName": "Ahmad",
  "lastName": "Mustapha",
  "state": "Kano",
  "phoneNumber": "+2347035636394",
  "password": "12345678",
  "addresses": ["Kabuga"]
}

###
