### Create Listing
POST http://localhost:3001/api/v1/listings/create
Content-Type: application/json

{
  "listingName": "{{$timestamp}}",
  "listingPrice": {{$randomInt}},
  "listingDesc": "{{$uuid}}",
  "listingAvailableDate": "MONDAY",
  "customisableOptions": [],
  "listingPhoto": []
}

### Update Listing
PUT http://localhost:3001/api/v1/listings/update/c368486c-c4c8-4535-9821-996c8d2815c0
Content-Type: application/json

{
  "id": "c368486c-c4c8-4535-9821-996c8d2815c0",
  "listingName": "Changed",
  "listingPrice": 566,
  "listingDesc": "6a0b0817-aa05-4878-9ae6-f425fa73926e",
  "listingAvailableDate": "TUESDAY",
  "customisableOptions": [],
  "listingPhoto": []
}

### Fetch Listings
GET http://localhost:3001/api/v1/listings
Accept: application/json


### Get Listing Info
GET http://localhost:3001/api/v1/listings/get-one/c368486c-c4c8-4535-9821-996c8d2815c0
Accept: application/json

### Delete Listing
DELETE http://localhost:3001/api/v1/listings/delete/8dc72165-420c-4005-8536-1b1dc87b2a04
Accept: application/json

