apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: imagynetech/eatlater-payment-service:1.13.1
          env:
            - name: RMQ_USERS_QUEUE
              value: USERS
            - name: RMQ_API_QUEUE
              value: API
            - name: RMQ_ORDERS_QUEUE
              value: ORDERS
            - name: RMQ_NOTIFICATION_QUEUE
              value: NOTIFICATION
            - name: RMQ_URI
              value: amqp://user:user@eatlater-rabbitmq:5672
            - name: RMQ_PAYMENT_QUEUE
              value: PAYMENT
            - name: RMQ_VENDORS_QUEUE
              value: VENDORS
            - name: MONGODB_URI
              value: mongodb://root:password123@eatlater-mongodb-headless:27017/
      imagePullSecrets:
        - name: regcred
