apiVersion: apps/v1
kind: Deployment
metadata:
  name: drivers-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drivers-service
  template:
    metadata:
      labels:
        app: drivers-service
        date: "{{ now | unixEpoch }}"
    spec:
      - name: drivers-service
        image: "{{ .Values.image.repository }}/drivers-service:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: http
            containerPort: 3003
            protocol: TCP
        env:
          {{- toYaml .Values.env | nindent 12 }}

