apiVersion: v1
kind: Service
metadata:
  name: driver-gateway
  namespace: {{ .Values.namespace.name }}
spec:
  type: ClusterIP
  ports:
    - port: 3003
      protocol: TCP
      targetPort: 3003
  selector:
    app: drivers-service
