version: 2.1
executors:
  node-executor:
    docker:
      - image: circleci/node:16

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Build
          command: yarn all:build

  test:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Test
          command: yarn ci:test

  codecov:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Upload to Codecov
          command: |
            curl -s https://codecov.io/bash | bash -s
            -t $CODECOV_TOKEN

  lint:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Lint
          command: npx --no-install eslint "{src,apps,libs,test}/**/*.ts"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - test
      - codecov
      - lint
