version: 2.1
orbs:
  node: circleci/node@5.0.2
  docker: circleci/docker@2.4.0
  codecov: codecov/codecov@3.3.0
jobs:
  docker-start:
    docker:
      - image: rabbitmq:latest
      - image: mongo:6
    steps:
      - run:
          name: Start Docker Daemon
          command: |
             dockerd --experimental
  build:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Build
          command: yarn all:build
  pull:
    executor: docker/machine
    steps:
      - checkout
      - docker/pull:
          images: mongo:6,rabbitmq:latest

  test:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Test
          command: yarn ci:test

  lint:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Lint
          command: npx --no-install eslint "{src,apps,libs,test}/**/*.ts"

workflows:
  build-deploy:
    jobs:
      - docker-start
      - build:
         requires:
           - docker-start
      - test
      - pull
      - lint
#  upload-to-codecov:
#    jobs:
#      - checkout
#      - codecov/upload
