export enum QUEUE_MESSAGE {
  VALIDATE_USER = 'validate_user',
  GET_USER = 'get_user',
  GET_USER_BY_PHONE = 'get_user_by_phone',
  CREATE_USER = 'create_user',
  VERIFY_PHONE = 'verify_phone',
  SEND_PHONE_VERIFICATION = 'send_phone_verification',
  UPDATE_USER_STATUS = 'update_user_status',
  GET_USER_LOCAL = 'get_user_with_email_password',
  GET_USER_JWT = 'get_user_with_id',
  GET_ADMIN_LOCAL = 'get_admin_with_username_password',
  GET_ADMIN_JWT = 'get_admin_with_id',
  GET_ADMIN = 'get_admin',
  GET_VENDOR = 'get_vendor',
  GET_VENDOR_SETTINGS = 'get_vendor_settings',
  GET_VENDOR_LOCAL = 'get_vendor_with_email_password',
  GET_VENDOR_JWT = 'get_vendor_with_id',
  CREATE_ADMIN = 'create_admin',
  CREATE_VENDOR = 'create_vendor',
  UPDATE_VENDOR_STATUS = 'update_vendor_status',
  VALIDATE_VENDOR = 'validate_vendor',
  VALIDATE_ADMIN = 'validate_admin',
  UPDATE_USER_PROFILE = 'update_user_profile',
  UPDATE_VENDOR_SETTING = 'update_vendor_settings',

  UPDATE_VENDOR_PROFILE = 'update_vendor_profile',
  UPDATE_ADMIN_STATUS = ' update_admin_status',
  DELETE_ADMIN = 'delete_admin',
  DELETE_USER_PROFILE = 'delete_user_profile',
  DELETE_VENDOR_PROFILE = 'delete_vendor_profile',
  GET_ALL_VENDORS = 'get_all_vendors',
  GET_VENDOR_WITH_LISTING = 'get_vendor_with_listing',
  GET_ALL_VENDORS_USERS = 'get_vendors_user',
  // Listing
  GET_ALL_LISTINGS = 'get_listings',
  GET_LISTING_INFO = 'get_listing_info',
  DELETE_LISTING = 'delete_listing',
  CREATE_LISTING = 'create_listing',
  UPDATE_LISTING = 'update_listing',
  GET_ALL_LISTING_ADMIN = 'get_listings_admin',
  GET_ALL_LISTING_USER = 'get_listings_user',

  //  Orders
  GET_ALL_ORDERS = 'get_all_orders',
  GET_SINGLE_ORDER_BY_REFNUM = 'get_single_order_by_refnum',
  GET_SINGLE_ORDER_BY_ID = 'get_single_order_by_id',
  GET_USER_ORDERS = 'get_users_order_by_id',
  GET_VENDORS_ORDERS = 'get_vendors_order_by_id',
  UPDATE_ORDER_STATUS = 'update_order_status',
  CREATE_ORDER = 'create_new_order',

  // Order status
  ORDER_STATUS_UPDATE = 'order_status_update',

  // Reviews
  REVIEW_CREATE = 'review_create',
  REVIEW_FIND_ONE = 'review_find_one',
  REVIEW_ADMIN_GET_ALL_IN_DB = 'review_admin_get_all_in_db',
  REVIEW_GET_LISTING_REVIEWS = 'review_get_listing_reviews',
  REVIEW_GET_VENDOR_REVIEWS = 'review_get_vendor_reviews',
  REVIEW_UPDATE_ONE = 'review_update_one',
  REVIEW_DELETE_ONE = 'review_delete_one',
  REVIEW_STATS_GET_VENDOR_REVIEWS = 'review_stats_get_vendor_reviews',
  REVIEW_STATS_GET_LISTING_REVIEWS = 'review_stats_get_listing_reviews',
}

export enum QUEUE_SERVICE {
  USERS_SERVICE = 'USERS',
  API_SERVICE = 'API',
  NOTIFICATION_SERVICE = 'NOTIFICATION',
  VENDORS_SERVICE = 'VENDORS',
  VENDORS_API = 'VENDORS_API',
  ADMIN_API = 'ADMIN_API',
  ADMIN_SERVICE = 'ADMIN',
  LISTINGS_SERVICE = 'LISTINGS',
  ORDERS_SERVICE = 'ORDERS',
  REVIEWS_SERVICE = 'REVIEWS',
}
