export enum SOCKET_MESSAGE {
  UPDATE_DRIVER_LOCATION = 'UPDATE_DRIVER_LOCATION',
  DRIVER_LOCATION_UPDATED = 'DRIVER_LOCATION_UPDATED',

  JOIN_ROOM = 'JOIN_ROOM',

  NEW_DELIVERY_TASK = 'NEW_DELIVERY_TASK',

  UPDATE_ORDER_STATUS = 'UPDATE_ORDER_STATUS'
}
