apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-gateway
  template:
    metadata:
      labels:
        app: admin-gateway
    spec:
      containers:
        - name: admin-gateway
          image: imagynetech/eatlater-admin-gateway:0.7.15
          ports:
            - containerPort: 3002
          env:
            - name: PORT
              value: '3002'
            - name: RMQ_URI
              value: amqp://user:user@eatlater-rabbitmq:5672
            - name: JWT_EXPIRATION
              value: '360000'
            - name: JWT_SECRET
              value: 64a5b5676eb9329c8978d3367fd7e1df5404ff886d16c0bc03edf7cc
            - name: RMQ_ADMIN_API_QUEUE
              value: ADMIN_API
            - name: RMQ_ADMIN_SERVICE_QUEUE
              value: ADMIN
            - name: RMQ_VENDORS_QUEUE
              value: VENDORS
            - name: RMQ_LISTINGS_QUEUE
              value: LISTINGS
            - name: RMQ_ORDERS_QUEUE
              value: ORDERS
      imagePullSecrets:
        - name: regcred
