apiVersion: apps/v1
kind: Deployment
metadata:
  name: listings
spec:
  replicas: 1
  selector:
    matchLabels:
      app: listings
  template:
    metadata:
      labels:
        app: listings
    spec:
      containers:
        - name: listings
          image: imagynetech/eatlater-listings-service:1.7.16
          env:
            - name: RMQ_URI
              value: amqp://user:user@eatlater-rabbitmq:5672
            - name: RMQ_LISTINGS_QUEUE
              value: LISTINGS
            - name: RMQ_ORDERS_QUEUE
              value: ORDERS
            - name: MONGODB_URI
              value: mongodb://root:password123@eatlater-mongodb-headless:27017/
      imagePullSecrets:
        - name: regcred
