apiVersion: apps/v1
kind: Deployment
metadata:
  name: review
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review
  template:
    metadata:
      labels:
        app: review
    spec:
      containers:
        - name: review
          image: imagynetech/eatlater-reviews-service:1.13.2
          env:
            - name: RMQ_URI
              value: amqp://user:user@eatlater-rabbitmq:5672
            - name: RMQ_NOTIFICATION_QUEUE
              value: NOTIFICATION
            - name: RMQ_API_QUEUE
              value: API
            - name: RMQ_USERS_QUEUE
              value: USERS
            - name: RMQ_REVIEW_QUEUE
              value: REVIEW
            - name: MONGODB_URI
              value: mongodb://root:password123@eatlater-mongodb-headless:27017/

      imagePullSecrets:
        - name: regcred
