apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: imagynetech/eatlater-users-service:1.8.16
          env:
            - name: RMQ_USERS_QUEUE
              value: USERS
            - name: RMQ_NOTIFICATION_QUEUE
              value: NOTIFICATION
            - name: RMQ_URI
              value: amqp://user:user@eatlater-rabbitmq:5672
            - name: MONGODB_URI
              value: mongodb://root:password123@eatlater-mongodb-headless:27017/
      imagePullSecrets:
        - name: regcred
