apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: imagynetech/eatlater-notification-service:1.9.0
          env:
            - name: RMQ_URI
              value: amqp://user:user@eatlater-rabbitmq:5672
            - name: RMQ_API_QUEUE
              value: API
            - name: RMQ_NOTIFICATION_QUEUE
              value: NOTIFICATION
            - name: RMQ_USERS_QUEUE
              value: USERS
            - name: LISTINGS_QUEUE
              value: LISTINGS
            - name: TWILIO_ACCOUNT_SID
              value: ACec965067efbc4019dd61a5aaf0c42369
            - name: TWILIO_AUTH_TOKEN
              value: 08e820054933084ca0a680ea7ea926c3
            - name: TWILIO_SERVICE_NAME
              value: VA42a1682c2eb59aa5af5ee339dad5eb8c
            - name: TWILIO_PHONE
              value: EatLater
      imagePullSecrets:
        - name: regcred
