apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
        date: "{{ now | unixEpoch }}"
    spec:
      containers:
        - name: admin-service
          image: "{{ .Values.image.repository }}-admin-service:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecrets }}

