apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: imagynetech/eatlater-admin-service:latest
          env:
            - name: RMQ_URI
              value: amqp://user:user@eatlater-rabbitmq:5672
            - name: JWT_EXPIRATION
              value: '360000'
            - name: JWT_SECRET
              value: 64a5b5676eb9329c8978d3367fd7e1df5404ff886d16c0bc03edf7cc
            - name: RMQ_ADMIN_API_QUEUE
              value: ADMIN_API
            - name: RMQ_VENDORS_API_QUEUE
              value: VENDORS_API
            - name: RMQ_VENDORS_QUEUE
              value: VENDORS
            - name: RMQ_ADMIN_SERVICE_QUEUE
              value: ADMIN
            - name: RMQ_ORDERS_QUEUE
              value: ORDERS
            - name: MONGODB_URI
              value: mongodb://root:password123@eatlater-mongodb-headless:27017/
      imagePullSecrets:
        - name: regcred
