
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: actions/setup-node@969bd2663942d722d85b6a8626225850c2f7be4b
        with:
          node-version: '16'
          cache: 'npm'

      - run: npm ci
      - run: npm run all:build

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: actions/setup-node@969bd2663942d722d85b6a8626225850c2f7be4b
        with:
          node-version: '16'
          cache: 'npm'

      - run: npm ci
      - run: npx --no-install eslint .

  docker-buildx:
    name: Docker Buildx
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ linux/amd64 ]
        app: [ admin-gateway, admin-service, vendor-gateway, vendors-service, api-gateway, users-service, notification-service ]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@8b122486cedac8393e77aa9734c3528886e4a1a8

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6

      - name: Build platforms
        uses: docker/build-push-action@c84f38281176d4c9cdb1626ffafcd6b3911b5d94
        with:
          push: false
          build-args: APP=${{ matrix.app }}
          platforms: ${{ matrix.platform }}
          tags: ghcr.io/eatlater/${{ matrix.app }}:latest
