apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: imagynetech/eatlater-orders-service:1.10.0
          env:
            - name: RMQ_URI
              value: amqp://user:user@eatlater-rabbitmq:5672
            - name: JWT_EXPIRATION
              value: '360000'
            - name: JWT_SECRET
              value: 64a5b5676eb9329c8978d3367fd7e1df5404ff886d16c0bc03edf7cc
            - name: RMQ_NOTIFICATION_QUEUE
              value: NOTIFICATION
            - name: RMQ_API_QUEUE
              value: API
            - name: RMQ_LISTINGS_QUEUE
              value: LISTINGS
            - name: RMQ_ORDERS_QUEUE
              value: ORDERS
            - name: MONGODB_URI
              value: mongodb://root:password123@eatlater-mongodb-headless:27017/

      imagePullSecrets:
        - name: regcred
