apiVersion: v1
kind: Service
metadata:
  name: admin-gateway
  namespace: {{ .Values.namespace.name }}
spec:
  type: ClusterIP
  ports:
    - port: 3002
      protocol: TCP
      targetPort: 3002
  selector:
    app: admin-gateway
