apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
        date: "{{ now | unixEpoch }}"
    spec:
      - name: users-service
        image: "{{ .Values.image.repository }}/users-service:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          {{- toYaml .Values.env | nindent 12 }}

