name: CI

on:
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@96f53100ba2a5449eb71d2e6604bbcd94b9449b5
      - uses: actions/setup-node@d82f92a0eb28e5699f87460c19fc2c674da76d01
        with:
          node-version: '16'
          cache: 'yarn'

      - run: yarn install --frozen-lockfile
      - run: yarn all:build

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        instance: [ 0, 1]
    env:
      GH_INSTANCE_TOTAL: 10
    steps:
      - uses: actions/checkout@96f53100ba2a5449eb71d2e6604bbcd94b9449b5
      - uses: actions/setup-node@d82f92a0eb28e5699f87460c19fc2c674da76d01
        with:
          node-version: '16'
          cache: 'yarn'

      - run: yarn install --frozen-lockfile
      - run: yarn ci:test
        env:
          GH_INSTANCE_INDEX: ${{ matrix.instance }}

      - uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          fail_ci_if_error: true
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@96f53100ba2a5449eb71d2e6604bbcd94b9449b5
      - uses: actions/setup-node@d82f92a0eb28e5699f87460c19fc2c674da76d01
        with:
          node-version: '16'
          cache: 'yarn'

      - run: yarn install --frozen-lockfile
      - run: npx --no-install eslint "{src,apps,libs,test}/**/*.ts"

  docker-buildx:
    name: Docker Buildx
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ linux/amd64 ]
        app: [ users-service, notification-service, vendors-service, admin-service, listings-service, admin-gateway, api-gateway, vendor-gateway, orders-service, review-service, payment-service ]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226

      - name: Build platforms
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825 # v4
        with:
          push: false
          build-args: APP=${{ matrix.app }}
          platforms: ${{ matrix.platform }}
          tags: imagynetech/eatlater-${{ matrix.app }}:latest
