name: CI

on:
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@96f53100ba2a5449eb71d2e6604bbcd94b9449b5
      - uses: actions/setup-node@d82f92a0eb28e5699f87460c19fc2c674da76d01
        with:
          node-version: '16'
          cache: 'yarn'

      - run: yarn install --frozen-lockfile
      - run: yarn all:build

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        instance: [ 0, 1]
    env:
      GH_INSTANCE_TOTAL: 10
    steps:
      - uses: actions/checkout@96f53100ba2a5449eb71d2e6604bbcd94b9449b5
      - uses: actions/setup-node@d82f92a0eb28e5699f87460c19fc2c674da76d01
        with:
          node-version: '16'
          cache: 'yarn'

      - run: yarn install --frozen-lockfile
      - run: yarn ci:test
        env:
          GH_INSTANCE_INDEX: ${{ matrix.instance }}

  codecov:
    name: Upload coverage reports to Codecov
    uses: codecov/codecov-action@v3
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@96f53100ba2a5449eb71d2e6604bbcd94b9449b5
      - uses: actions/setup-node@d82f92a0eb28e5699f87460c19fc2c674da76d01
        with:
          node-version: '16'
          cache: 'yarn'

      - run: yarn install --frozen-lockfile
      - run: npx --no-install eslint "{src,apps,libs,test}/**/*.ts"
