#name: Build and Deploy Microservices to DO [PRODUCTION]
#
#on:
#  push:
#    branches:
#      - main
#jobs:
#  build-and-push:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        service:
#          - admin-gateway
#          - admin-service
#          - api-gateway
#          - drivers-service
#          - listings-service
#          - location-service
#          - notification-service
#          - orders-service
#          - payment-service
#          - reviews-service
#          - users-service
#          - vendors-service
#          - vendor-gateway
#
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#
#      - name: Log in to Digital Ocean Container Registry
#        uses: docker/login-action@v2
#        with:
#          registry: ${{ secrets.DIGITAL_OCEAN_REGISTRY }}
#          username: ${{ secrets.DIGITAL_OCEAN_USERNAME }}
#          password: ${{ secrets.DIGITAL_OCEAN_PASSWORD }}
#
#      - name: Build and Push Docker Image
#        run: |
#          docker buildx build \
#            --platform linux/amd64 \
#            --push \
#            -t "${{ secrets.DIGITAL_OCEAN_REGISTRY }}/nana-hydra/production-${{ matrix.service }}" \
#            -f ./apps/${{ matrix.service }}/Dockerfile .
