name: OSS Governance

on:
  push:
    branches: [ main ]
    paths: [ .github/labels.yml ]

permissions:
  contents: read
  issues: write

jobs:
  Labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@96f53100ba2a5449eb71d2e6604bbcd94b9449b5

      - uses: micnncim/action-label-syncer@3abd5ab72fda571e69fffd97bd4e0033dd5f495c
        with:
          prune: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
