name: OSS Governance

on:
  push:
    branches: [ main ]
    paths: [ .github/labels.yml ]

permissions:
  contents: read
  issues: write

jobs:
  Labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9a9194f87191a7e9055e3e9b95b8cfb13023bb08

      - uses: micnncim/action-label-syncer@3abd5ab72fda571e69fffd97bd4e0033dd5f495c
        with:
          prune: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
