name: OSS Governance

on:
  pull_request_target:
    types: [ opened, edited, synchronize ]

permissions:
  contents: read
  issues: write
  pull-requests: write
  statuses: write
  checks: write

jobs:
  Labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: fuxingloh/multi-labeler@77f19bc5b512f2e04340b914a9043d378305284c
        with:
          config-path: .github/labeler.yml
