name: Lint PR

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@5369185dc9812f174fa58b03b13b79920b68f8e1
        with:
          subjectPattern: ^(?![A-Z]).+$
          validateSingleCommit: true
          requireScope: true
          types: |
            fix
            feature
            chore
            docs
            style
            refactor
            performance
            test
            ci
            build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
