name: Release Apps

on:
  release:
    types: [ published ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

env:
  APPS: 'notification-service,vendors-service,users-service,admin-service,listings-service,admin-gateway,api-gateway,vendor-gateway,orders-service,reviews-service, payment-service'

jobs:
  build:
    if: github.event_name != 'pull_request' || (github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]')
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        app: [
          notification-service,
          vendors-service,
          users-service,
          admin-service,
          listings-service,
          admin-gateway,
          api-gateway,
          vendor-gateway,
          orders-service,
          reviews-service,
          payment-service
        ]
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
        with:
          repository: imagyne/aristotle
          ref: main
          token: ${{ secrets.PAT }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7 # v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4c0219f9ac95b02789c1075625400b2acbff50b1 # v2

      - name: Login to Docker Hub
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Resolve Tags
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6
        id: tags
        env:
          APP: ${{ matrix.app }}
        with:
          script: return require('./.github/scripts/release-tags.js')({ context })
          result-encoding: string
      - name: Check tags
        run: echo ${{ steps.tags.outputs.result }}
      - name: Build & Publish
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825 # v4
        with:
          context: .
          push: true
          build-args: APP=${{ matrix.app }}
          platforms: linux/amd64
          tags: ${{ steps.tags.outputs.result }}

  report:
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository && github.actor != 'dependabot[bot]'
    name: Report
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@96f53100ba2a5449eb71d2e6604bbcd94b9449b5

      - name: Create Report
        uses: actions/github-script@d556feaca394842dc55e4734bf3bb9f685482fa0
        id: report
        with:
          script: return require('./.github/scripts/release-report.js')({ context })
          result-encoding: string

      - name: Post Report
        uses: marocchino/sticky-pull-request-comment@f61b6cf21ef2fcc468f4345cdfcc9bda741d2343
        with:
          header: release
          message: ${{ steps.report.outputs.result }}
