name: Publish Staging Environment to Aptible
on:
  workflow_dispatch:
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - admin-gateway
          - admin-service
          - api-gateway
          - drivers-service
          - listings-service
          - location-service
          - notification-service
          - orders-service
          - payment-service
          - reviews-service
          - users-service
          - vendor-gateway
          - vendors-service

    steps:
      - name: Checkout code
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838 # v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: af-south-1

      - name: Login to AWS ECR
        run: aws ecr get-login-password --region af-south-1 | docker login --username AWS --password-stdin 814105780686.dkr.ecr.af-south-1.amazonaws.com

      - name: Deploy to Aptible
        uses: aptible/aptible-deploy-action@386b3a22144b11c5a5797522eccfde7a7baad4c4 # v1
        with:
          username: ${{ secrets.APTIBLE_USERNAME }}
          password: ${{ secrets.APTIBLE_PASSWORD }}
          environment: ${{ env.APTIBLE_ENVIRONMENT }}
          app: ${{ matrix.service }}
          docker_img: "814105780686.dkr.ecr.af-south-1.amazonaws.com/${{ matrix.service }}-stating:latest"
